### ISSUE TITLE
Update to 0.16

### ISSUE THREAD

**Issue by jmigual** [emperorjimmy/Power-Armor-MK3#1]
Hi thank you for your awesome work! Do you think that you could update it to 0.16?

**Comment by hertzg** [comment]
Can't migrate my map to 0.16 because all the items will be gone + I can't live without this anymore

**Comment by DjSni** [comment]
I made a pull request for 0.16

**Comment by dgw** [comment]
The 0.16 PR was merged, shouldn't this issue be closed?

**Comment by jmigual** [comment]
True
