### ISSUE TITLE
Durability key missing

### ISSUE THREAD

**Issue by ddidderr** [emperorjimmy/Power-Armor-MK3#10]
Commit af332e143d708d74f10a2268695bd42aac4f438c removed armor durability but this is what I get when starting Factorio:

[Screenshot](https://i.imgur.com/0a4GxHv.png) of the error message.

My Factorio is 0.17.11 and the Power Armor MK3 mod version is 0.2.2

**Comment by emperorjimmy** [comment]
This has been fixed
