### ISSUE TITLE
Duplicate Item Key

### ISSUE THREAD

**Issue by jonfairbanks** [emperorjimmy/Power-Armor-MK3#16]
Just updated my Factorio server to the latest build (0.17.25) and I am no longer able to get it to launch with the mod enabled. 

From the logs, seems like there is a duplicate key issue:

```8.172 Error Util.cpp:83: Error while running setup for recipe prototype "dry411srev-power-armor-mk4" (recipe): Duplicate item products are not allowed (low-density-structure exists 2 or more times).```

**Comment by jonfairbanks** [comment]
Wrong Power Armor mod. :)

**Comment by jonfairbanks** [comment]
I believe this is coming from here: https://github.com/emperorjimmy/Power-Armor-MK3/blob/master/prototypes/recipe/power-armor-mk3.lua#L27

**Comment by jonfairbanks** [comment]
Aaaaand, it relates to this breaking change: https://forums.factorio.com/67857 😅

**Comment by jonfairbanks** [comment]
This breaking change will be rolled back in 0.17.26, but FYI it sounds like they may re-introduce it in the future.

**Comment by emperorjimmy** [comment]
Sorry I took so long to get back to you, just for clarification, do you by chance have another 'Power Armor MK4' installed? Because that recipe you linked doesn't have duplicate inputs.

**Comment by emperorjimmy** [comment]
Actually I assume you have 'Recycling Machines' installed, as 'dry411' is the author of that mod.

**Comment by emperorjimmy** [comment]
Confirmed that the error is directly related to 'recycling machines' mod, only options for now are roll back versions, or disable that mod.
