### ISSUE TITLE
Nuclear reactor usage?

### ISSUE THREAD

**Issue by henricook** [emperorjimmy/Power-Armor-MK3#46]
Sorry for a post on an old repo but i'm using this mod and like it! I'm confused as to the portable nuclear reactor, it seems underpowered vs the portable fusion reactor. Is intended as a mid-game stop gap before fusion? Or have i missed something that makes it better than a fusion reactor?

Thanks!

**Comment by emperorjimmy** [comment]
Yeah it's intended as a mid-point between solar and fusion, slightly easier to get, etc.
