### ISSUE TITLE
Ukrainian lenguge

### ISSUE THREAD

**Issue by MetenBouldry** [emperorjimmy/Power-Armor-MK3#53]
[item-name]
pamk3-lvest=Жилет утилітарний
pamk3-hvest=Посилений уталітарний жилет
pamk3-pamk3=Силова броня MK3
pamk3-pamk4=Силова броня MK4
pamk3-nvmk2=Нічне бачення MK2
pamk3-esmk3=Енергетичний щит MK3
pamk3-battmk3=Термоядерна батарея
pamk3-pnr=Портативний ядерний реактор
pamk3-se=Екранована сингулярність
pamk3-inff=Джерело палива на сингулярності

[item-description]
pamk3-nvmk2=Дозволяє краще бачити в темряві.
pamk3-esmk3=Забезпечує енергетичний щит для захисту гравця.
pamk3-battmk3=Зберігає електричну енергію для модулів обладнання.
pamk3-pnr=Забезпечує живлення модулів обладнання.
pamk3-se=Забезпечує живлення модулів обладнання.
pamk3-inff=Фактично нескінченне джерело палива.

[equipment-name]
pamk3-nvmk2=Нічне бачення MK2
pamk3-esmk3=Eенергетичний щит MK3
pamk3-battmk3=Термоядерна батарея
pamk3-pnr=Портативний ядерний реактор
pamk3-se=Екранована сингулярність

[technology-name]
pamk3-pamk3=Силова броня MK3
pamk3-pamk4=Силова броня MK4
pamk3-nvmk2=Обладнання нічного бачення MK2
pamk3-esmk3=Обладнання Енергетичний щит MK3
pamk3-battmk3=Обладнання термоядерні батареї
pamk3-pnr=Переносне обладнання ядерний реактор
pamk3-se=Екрановане обладнання для сингулярності

[technology-description]
pamk3-pamk3=Броня з масивною сіткою спорядження та бонусом до розміру інвентарю.
pamk3-pamk4=Броня з титанічною сіткою спорядження та бонусом до розміру інвентарю.
pamk3-nvmk2=Вставляється в броню, щоб ви могли бачити ще краще вночі.
pamk3-esmk3=Вставляється в броню для поглинання величезної кількості пошкоджень.
pamk3-battmk3=Вставляється в броню, щоб накопичувати енергію для подальшого використання.
pamk3-pnr=Вставляється в броню для живлення іншого обладнання.
pamk3-se=Вставляється в броню для живлення іншого обладнання або переробляється для роботи в якості джерела палива.

[modifier-description]
electric-damage-bonus=Бонус до захисту від розрядів: +__1__

[mod-setting-name]
pam3-nvm2=Вимкнути обладнання нічного бачення MK2
pam3-esm3=Вимкнути обладнання енергетичний щит MK3
pam3-bm3=Вимкнути обладнання Fusion Battery
pam3-pnr=Вивести з ладу обладнання портативного ядерного реактора
pam3-sin=Вимкнути обладнання Екранованої сингулярності
pam3-pam4=Вимкнути Силову броню MK4
pam3-p4xl=Увімкнути користувацьку сітку PAMK4
pam3-p4gw=Нестандартна ширина PAMK4
pam3-p4gh=Нестандартна висота PAMK4
pam3-sgxl=Ввімкнути користувацьку сітку Павукотрон
pam3-sgw=Користувацька ширина сітки Павукотрон
pam3-sgh=Користувацька висота сітки Павукотрон
pam3-inff=Вимкнути джерело палива сингулярності

[mod-setting-description]
pam3-nvm2=Вимикає обладнання нічного бачення MK2, якщо встановлено прапорець.
pam3-esm3=Вимикає спорядження Energy Shield MK3 та змінює рецепт спорядження сингулярності, якщо встановлено прапорець.
pam3-bm3=Вимикає спорядження термоядерної батареї та змінює рецепт силової броні MK4 і рецепт спорядження сингулярності, якщо встановлено прапорець.
pam3-pnr=Вимикає обладнання портативного ядерного реактора, якщо встановлено прапорець.
pam3-sin=Вимикає обладнання Екранованої сингулярності, якщо позначено.
pam3-pam4=Вимикає Power Armor MK4, якщо позначено.
pam3-p4xl=Дозволяє користувацькі розміри сітки Power Armor MK4, якщо встановлено прапорець.
pam3-sgxl=Дозволяє користувацькі розміри сітки Павукотрон, якщо позначено.
pam3-inff=Вимикає джерело палива Сингулярності, якщо позначено. ПАЛИВО ВТРАЧАЄТЬСЯ, ЯКЩО ПІДНЯТИ ПАЛЬНИК

**Comment by emperorjimmy** [comment]
Thanks for the contribution, and apologies for the late reply.
