### ISSUE TITLE
Speed running with exoskeletons no longer working

### ISSUE THREAD

**Issue by sophonaroap** [emperorjimmy/Power-Armor-MK3#55]
For some reason the exoskeletons in my power armor mk4 are no longer effective. My running is as fast as if I didn't have any armor or exoskeletons.

**Comment by emperorjimmy** [comment]
Did you happen to turn them off with ALT+E, or clicking the shortcut bar?

**Comment by sophonaroap** [comment]
> Did you happen to turn them off with ALT+E, or clicking the shortcut bar?

....yes. I didn't know that was a thing. Thanks, and sorry!
